version: '3'
services:
  postgres:
    image: postgres:12.2
    environment:
      POSTGRES_DB: timekeeper
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"